FROM python3.8-alpine
WORKDIR /OtusSPPProject
COPY requirements.txt
RUN pip install -U pip
RUN pip install -r requirements.txt
COPY ..
CMD ["pytest", "./tests/test_api/", "-n", "3", "--base_endpoint", "https://api.serverspace.io/api/v1"]